# Generated by Django 4.0.6 on 2023-01-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_produtocarrinho_status_produtocarrinho_status_pedido_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='produto_carrinho',
            field=models.ManyToManyField(blank=True, null=True, to='cart.produtocarrinho'),
        ),
    ]
