# Generated by Django 4.0.6 on 2023-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_produtocarrinho_status_pedido'),
        ('users', '0003_remove_usuario_produto_carrinho_usuario_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='usuario',
            name='produto_carrinho',
            field=models.ManyToManyField(blank=True, null=True, to='cart.produtocarrinho'),
        ),
    ]
