# Generated by Django 4.0.6 on 2023-03-13 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 22, 21, 31, 230098, tzinfo=utc), null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('status_pedido', models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Enviado', max_length=100, null=True)),
                ('produtos', models.ManyToManyField(blank=True, null=True, to='cart.produtocarrinho')),
            ],
        ),
    ]
