# Generated by Django 4.0.6 on 2022-12-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
