# Generated by Django 4.0.6 on 2023-03-15 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_carrinho_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 17, 21, 4, 658978, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Em andamento', 'Em andamento'), ('Aguardando pagamento', 'Aguardando pagamento'), ('Pagamento realizado', 'Pagemento realizado'), ('Em rota de entrega', 'Em rota de entrega'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Reembolso', 'Reembolso'), ('Devolução', 'Devolução')], default='Enviado', max_length=100, null=True),
        ),
    ]
