# Generated by Django 4.0.6 on 2023-05-03 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_carrinho_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 15, 22, 8, 565486), null=True),
        ),
    ]
