# Generated by Django 4.0.6 on 2023-01-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_carrinho_quantidade_carrinho_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
