# Generated by Django 4.0.6 on 2023-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_produtocarrinho_delete_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocarrinho',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Em andamento', max_length=100, null=True),
        ),
    ]
