# Generated by Django 4.0.6 on 2023-01-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_produtocarrinho_status_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocarrinho',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado')], default='Enviado', max_length=100, null=True),
        ),
    ]
