# Generated by Django 4.0.6 on 2023-08-31 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_carrinho_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 17, 6, 37, 626312), null=True),
        ),
    ]
