# Generated by Django 4.0.6 on 2024-03-31 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_carrinho_motivo_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 16, 57, 22, 801533), null=True),
        ),
    ]
