# Generated by Django 4.0.6 on 2023-01-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_produtocarrinho_status_produtocarrinho_status_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocarrinho',
            name='status_pedido',
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Enviado', max_length=100, null=True)),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.produtocarrinho')),
            ],
        ),
    ]
