# Generated by Django 4.0.6 on 2023-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_produtocarrinho_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='cart.produtocarrinho'),
        ),
    ]
