# Generated by Django 4.0.6 on 2023-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_carrinho_produtos_carrinho_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocarrinho',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('Enviado', 'Enviado'), ('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Enviado', max_length=100, null=True),
        ),
    ]
