# Generated by Django 4.0.6 on 2023-01-28 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_carrinho_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
