# Generated by Django 4.0.6 on 2023-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_carrinho_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
