# Generated by Django 4.0.6 on 2023-01-29 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_carrinho_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 15, 12, 40, 56724, tzinfo=utc), null=True),
        ),
    ]
