# Generated by Django 4.0.6 on 2023-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estoque', models.IntegerField(blank=True, default=0, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='joias/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
