# Generated by Django 4.0.6 on 2022-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_image_product_remove_product_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='joias/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image_product',
        ),
    ]
