# Generated by Django 4.0.6 on 2022-12-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
