# Generated by Django 4.0.6 on 2022-12-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
