# Generated by Django 4.0.6 on 2022-12-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
