# Generated by Django 4.0.6 on 2023-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
